### ISSUE TITLE
Does react-native-tvos app supported in Roku, PS4, Xbox and Amazon firestick ?

### ISSUE THREAD

**Issue by mehthabux** [react-native-tvos/react-native-tvos#122]
I know its a discussion.
I'm developing an android and tvos tv app. I would like to know i can run this apps on Roku, PS4, Xbox and Amazon firestick

**Comment by dlowder-salesforce** [comment]
This repo does not support that.  It looks like https://renative.org/ is attempting to do this. There is an issue there with a discussion on how to integrate this repo with that system: https://github.com/pavjacko/renative/issues/583

**Comment by CodyDunlap** [comment]
You can actually run this on FireTV as well, as that's just Android. There are some features that are missing, namely anything that depends on Google Play services. I'm not familiar with Xbox and PS4, but good luck getting anything to work with Roku. I've been looking for something like that as well, and even [https://renative.org/](https://renative.org/) doesn't seem to support that. The only library I have found that claims to do that is [Youi.tv](https://www.youi.tv/) but it's not free and their solution for React Native on Roku is unique.

**Comment by safaiyeh** [comment]
react-native-windows works on Xbox, not sure which port is trying to do PS

**Comment by pavjacko** [comment]
For those who are interested, I'm planning to add support for dedicated engine which will use `react-native-tvos` instead of `react-native`

some initial prep work started already: https://github.com/pavjacko/renative/tree/develop/packages/rnv-engine-rn-tvos

this will allow devs to switch to this by simply setting `"engine": "engine-rn-tvos"` via `renative.json` to ensure easy migration

expected release will be rnv@0.33.0 (currently at 0.31 with soon to be released 0.32)

**Comment by hbbrawer-twitch** [comment]
Hi @pavjacko,

Thanks for all the info in this thread! I was curious if you had made any progress regarding support for PS4?

Thank you,
Harlan
