### ISSUE TITLE
AndroidTv: onLongPress not working with remote control

### ISSUE THREAD

**Issue by mhovanisian** [react-native-tvos/react-native-tvos#232]
onLongPress (Touchable components) not working with remote control but only with mouse press

https://user-images.githubusercontent.com/87751719/139437791-a74c6fee-2db3-4b2a-bdc4-d646fb7efd4f.mp4

**Comment by douglowder** [comment]
@mhovanisian I have a simple implementation working that sends `longSelect` instead of `select` if the center button is pressed for more than 1 second.  In testing this, it seems that Android TV starts sending multiple down events if the button is pressed for a long time, so it would be possible to detect a long press that way as well.  Please take a look at #238 and let me know your thoughts.

**Comment by mhovanisian** [comment]
@douglowder looks good, thank you

**Comment by mhovanisian** [comment]
Hi @douglowder, is the next release coming soon ?

**Comment by douglowder** [comment]
Yes indeed

**Comment by douglowder** [comment]
@mhovanisian this is now released in 0.64.2-5
