### ISSUE TITLE
Upgrade Plan/Timeline

### ISSUE THREAD

**Issue by miblanchard** [react-native-tvos/react-native-tvos#274]
With the core team's stated goal of more frequent react-native releases, do you have an opinion/corresponding target for how closely this fork will follow the main react-native releases?    
I’m in no way trying to ask when a specific react-native release will appear in this fork.  I’m just curious to understand what you would prefer.

**Comment by douglowder** [comment]
@miblanchard this is a very good question, and the answer will depend very strongly on the nature of the releases from the core team.

In the past, it has been very common for each release to have quite a lot of changes under the hood that break TV (especially Apple TV), so quite a bit of work is needed to take the release and cleanly patch in the TV support.

If it turns out that RN core is going to be a bit more stable going forward, with less large changes between releases, then I would have an easier time keeping up with the pace of core development.

At the moment I can support getting a TV release out for every other RN core release. Also, if a particular RN core version has important changes that developers really need (e.g. a move to React 18, or full Fabric support, etc.), then I would prioritize supporting that release.

**Comment by douglowder** [comment]
Note that 0.68 upgrade is already happening, see #281

**Comment by douglowder** [comment]
0.68.1 coming soon

**Comment by douglowder** [comment]
I'm going to go ahead and close this, and will make release announcements in the new "Discussions" area going forward. At this time the latest release is https://github.com/react-native-tvos/react-native-tvos/releases/tag/v0.69.5-1, see #362
