### ISSUE TITLE
selected tab changes automatically after clicking on button

### ISSUE THREAD

**Issue by IM-Mukesh** [react-native-tvos/react-native-tvos#307]
### Description

@douglowder 

when we are clicking on 'Go To Cart' button then onPress we are setting 'cart' page as Selected tab but by default after setting it for less than 1 sec it automatically sets the product page.

**we are loading both PRODUCTS and CART together based on the interaction we are displaying it using display property but it calls onFocus automatically 'Products' tab even though we are setting the 'cart' tab to be focused.**

### Version

react-native-cli: 2.0.1 react-native: 0.66.3-3

### Output of `npx react-native info`

info Fetching system and libraries information...
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
    Memory: 11.76 GB / 30.97 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: Not Found
    react-native-tvos:  0.66.3-3 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

when we are clicking on 'Go To Cart' button then onPress we are setting 'cart' page as Selected tab but by default after setting it for less than 1 sec it automatically sets the product page.

**we are loading both PRODUCTS and CART together based on the interaction we are displaying it using display property but it calls onFocus automatically 'Products' tab even though we are setting the 'cart' tab to be focused.**

### Snack, code example, screenshot, or link to a repository

https://user-images.githubusercontent.com/75795724/167789139-6095eb4d-3c9b-4524-b55d-5c3704fe6260.mp4

**Comment by douglowder** [comment]
Please provide the source code for your UI, and any dependencies you are using (e.g. react-navigation).

**Comment by ratz6** [comment]
Hey @douglowder ! 
Here we have two TouchableHighlights (Products and Cart )Tab displayed in a component and the content under each Tab is displayed based on the Tab (Touchable Highlight click). 

![image](https://user-images.githubusercontent.com/77700933/168685309-cb28837a-3dfb-4f54-b555-80d02af7f05d.png)

We are using refs to handle the focus similar to https://github.com/dev-seb/react-native-tv-demo (instead of react-native we use react-native-tvos unlike the above example) 
and are not using react-navigation as we faced issues with react-navigation early on while capturing it's reference to show focusable tabs/products.

So right now, when I add a product to cart, I'm triggering the ref to be focused on Cart Tab but the Products tab reference is also being called unknowingly. 
similarly when I delete an element from cart, the ref should be focused within the Cart Tab but the Product tab ref is triggered along with the focus shifting there.

Do you think of anything which might cause the issue ? Or do you know of any other way to achieve this ?
Let me know if you need more info on this.

Cheers!

**Comment by douglowder** [comment]
Are you setting `hasTVPreferredFocus` on the new items? Depending on when this is done, some other item could get focus afterwards.

Again, it would be helpful if you provide a working example that shows the issue.

**Comment by ratz6** [comment]
Hey @douglowder Uploaded a Video of how the transition is happening and yes we have set 'hasTVPreferredFocus' on Product.
Sorry for the late reply , we are not using react-navigation and handling navigation through refs as mentioned above (just a reminder).
PFB the code snippets and video. Let me know if you need anything to understand the issue 

https://user-images.githubusercontent.com/77700933/171370378-e79237a4-964e-4cf2-b8d9-09922f49eb18.mp4

Product > 
![image](https://user-images.githubusercontent.com/77700933/171370848-245e937a-b0a5-4473-9898-b3d795f52bc7.png)
Cart > 
![image](https://user-images.githubusercontent.com/77700933/171370895-b39e66c3-66b8-4338-8f38-15913790683e.png)

Custom Component > 
![image](https://user-images.githubusercontent.com/77700933/171370972-a710d58b-11f8-4529-8deb-0936e0f0b558.png)

**Comment by douglowder** [comment]
Closing this, as there is no code sample provided to reproduce the issue.
