### ISSUE TITLE
hasTVPreferredFocus didn't work with @react-navigation/native and @react-navigation/native-stack

### ISSUE THREAD

**Issue by NazarKuryl0** [react-native-tvos/react-native-tvos#670]
### Description

hasTVPreferredFocus didn't autofocus needed element, but WITHOUT @react-navigation/native and @react-navigation/native-stack all works fine

### React Native Version

npm:react-native-tvos@0.71.12-0

### Output of `npx react-native info`

System:
    OS: macOS 13.6.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 184.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
    Watchman: 2023.12.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11255304
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.9 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: Not Found
    react-native-macos: Not Found
    react-native-tvos:  0.71.12-0 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1. init app with npm:react-native-tvos@0.71.12-0
2. add next libs:@react-navigation/native, @react-navigation/native-stack, react-native-screens
3. add this code to App.js

```
import * as React from 'react';
import {
  NavigationContainer,
  createNavigationContainerRef,
} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {LogBox, View, TouchableOpacity, Text} from 'react-native';

const ENVS = ['INT', 'PROD'];
LogBox.ignoreAllLogs();
const Stack = createNativeStackNavigator();

export const navigationRef = createNavigationContainerRef();

class SwitchENVPage extends React.Component {
  render() {
    return (
      <View>
        {ENVS.map((item, index) => (
          <TouchableOpacity
            key={item}
            ref={ref => (this[item] = ref)}
            style={{
              flexDirection: 'row',
              alignItems: 'center',
            }}
            hasTVPreferredFocus={index === 1}>
            <Text>{item}</Text>
          </TouchableOpacity>
        ))}
      </View>
    );
  }
}

class App extends React.Component {
  render() {
    return (
      <NavigationContainer ref={navigationRef}>
        <Stack.Navigator
          initialRouteName="SwitchENVPage"
          screenOptions={{headerShown: false}}>
          <Stack.Screen
            name="SwitchENVPage"
            component={SwitchENVPage}
            options={{
              headerBackVisible: false,
              fullScreenGestureEnabled: true,
            }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    );
  }
}

export default App;
```

### Snack, screenshot, or link to a repository

![Simulator Screenshot - Apple TV - 2024-02-22 at 16 17 52](https://github.com/react-native-tvos/react-native-tvos/assets/57804534/c4d61e6e-e819-4f07-967c-d0f18335b000)

**Comment by NazarKuryl0** [comment]
current workarround - with refs like this 
```
setTimeout(() => {
      this.ref.requestTVFocus();
    }, 500);
```

**Comment by douglowder** [comment]
If you need this, we would recommend using `@react-navigation/stack` for now.

**Comment by psysize** [comment]
@douglowder Do we know anything more about what might have caused this? I'm happy to try dive in and take a look at any relevant areas.

We're cautious about swapping out `@react-navigation/native` for possible performance degradation.

**Comment by danychi** [comment]
@douglowder I am facing the same issue, is there any plans to re-open it and tackle it? 👀

**Comment by psysize** [comment]
I've been trying to isolate this issue locally. It's quite difficult to replicate immediately but I am able to do so using the rn-tester package within the repo without `@react-navigation/native` or `@react-navigation/native-stack`.

It seems to happen when mounting / unmounting Pressables with `hasTVPreferredFocus` enabled, sometimes.

**This issue doesn't happen with fabric enabled.**

Basically `setTVPreferredFocus` in `ReactViewManager.java` is triggered again after blurring and / or focusing on another element, forcing it back.

```
@ReactProp(name = "hasTVPreferredFocus")
  public void setTVPreferredFocus(ReactViewGroup view, boolean hasTVPreferredFocus) {
    if (hasTVPreferredFocus) {
      view.setFocusable(true);
      view.setFocusableInTouchMode(true);
      view.requestFocus();
    }
  }`
```

The video below first demonstrates the expected `hasTVPreferredFocus` behaviour (true on item 1).

1. Navigate away (unmounting)
2. Come back to the elements with `hasTVPreferredFocus`.
3. Try move the focus away from the element with `hasTVPreferredFocus`.

Repeat steps 1 - 2 until the issue is observed.

Observe that it sometimes forces the focus back to the element that has `hasTVPreferredFocus` set to true.

[tvHasPreferredFocus.webm](https://github.com/user-attachments/assets/2760fb5f-c2be-4c18-a436-29aee3dd7546)

_I don't think it's relevant to the issue but to build locally I also had to downgrade the CMake version from to `3.18.1` from `3.22.1`._
